# Generated by Django 2.2 on 2020-04-14 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20200413_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('initial_design_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delta_design_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('result_design_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('initial_development_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delta_development_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('result_development_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('initial_testing_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delta_testing_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('result_testing_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
