# Generated by Django 2.2 on 2020-04-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectchanges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectchanges',
            old_name='delta_design_time',
            new_name='delta_actual_design',
        ),
        migrations.RenameField(
            model_name='projectchanges',
            old_name='delta_development_time',
            new_name='delta_actual_development',
        ),
        migrations.RenameField(
            model_name='projectchanges',
            old_name='delta_testing_time',
            new_name='delta_actual_testing',
        ),
        migrations.RenameField(
            model_name='projectchanges',
            old_name='initial_design_time',
            new_name='initial_actual_design',
        ),
        migrations.RenameField(
            model_name='projectchanges',
            old_name='initial_development_time',
            new_name='initial_actual_development',
        ),
        migrations.RenameField(
            model_name='projectchanges',
            old_name='initial_testing_time',
            new_name='initial_actual_testing',
        ),
        migrations.RenameField(
            model_name='projectchanges',
            old_name='result_design_time',
            new_name='result_actual_design',
        ),
        migrations.RenameField(
            model_name='projectchanges',
            old_name='result_development_time',
            new_name='result_actual_development',
        ),
        migrations.RenameField(
            model_name='projectchanges',
            old_name='result_testing_time',
            new_name='result_actual_testing',
        ),
    ]
