# Generated by Django 2.2 on 2020-04-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200414_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectchanges',
            name='delta_actual_design',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='projectchanges',
            name='delta_actual_development',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='projectchanges',
            name='delta_actual_testing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='projectchanges',
            name='initial_actual_design',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='projectchanges',
            name='initial_actual_development',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='projectchanges',
            name='initial_actual_testing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='projectchanges',
            name='result_actual_design',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='projectchanges',
            name='result_actual_development',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='projectchanges',
            name='result_actual_testing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
