# Generated by Django 2.2 on 2020-04-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200414_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttagrelation',
            name='attached_date',
            field=models.DateTimeField(),
        ),
    ]
