# Generated by Django 2.2 on 2020-04-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200414_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttagrelation',
            name='attached_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
