# Generated by Django 2.2 on 2020-04-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200415_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttagrelation',
            name='attached_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
